//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef VX_IO_VXPAD_WXCRAFTER_BASE_CLASSES_H
#define VX_IO_VXPAD_WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/statbox.h>
#include <wx/statbmp.h>
#include <wx/menu.h>
#include <wx/toolbar.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

class MainFrameBaseClass : public wxFrame
{
protected:
    wxStaticBitmap* m_staticBitmap51;
    wxStaticBitmap* m_staticBitmap53;
    wxStaticBitmap* m_staticBitmap55;
    wxStaticBitmap* m_staticBitmap57;
    wxStaticBitmap* m_staticBitmap59;
    wxStaticBitmap* m_staticBitmap61;
    wxStaticBitmap* m_staticBitmap13;
    wxStaticBitmap* m_staticBitmap15;
    wxStaticBitmap* m_staticBitmap17;
    wxStaticBitmap* m_staticBitmap19;
    wxStaticBitmap* m_staticBitmap21;
    wxStaticBitmap* m_staticBitmap23;
    wxStaticBitmap* m_staticBitmap25;
    wxStaticBitmap* m_staticBitmap27;
    wxStaticBitmap* m_staticBitmap29;
    wxStaticBitmap* m_staticBitmap31;
    wxStaticBitmap* m_staticBitmap37;
    wxStaticBitmap* m_staticBitmap39;
    wxStaticBitmap* m_staticBitmap41;
    wxStaticBitmap* m_staticBitmap43;
    wxStaticBitmap* m_staticBitmap45;
    wxStaticBitmap* m_staticBitmap47;
    wxMenuBar* m_menuBar;
    wxMenu* m_name6;
    wxMenuItem* m_menuItem7;
    wxMenu* m_name8;
    wxMenuItem* m_menuItem9;
    wxToolBar* m_mainToolbar;

protected:
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticBitmap* GetStaticBitmap51() { return m_staticBitmap51; }
    wxStaticBitmap* GetStaticBitmap53() { return m_staticBitmap53; }
    wxStaticBitmap* GetStaticBitmap55() { return m_staticBitmap55; }
    wxStaticBitmap* GetStaticBitmap57() { return m_staticBitmap57; }
    wxStaticBitmap* GetStaticBitmap59() { return m_staticBitmap59; }
    wxStaticBitmap* GetStaticBitmap61() { return m_staticBitmap61; }
    wxStaticBitmap* GetStaticBitmap13() { return m_staticBitmap13; }
    wxStaticBitmap* GetStaticBitmap15() { return m_staticBitmap15; }
    wxStaticBitmap* GetStaticBitmap17() { return m_staticBitmap17; }
    wxStaticBitmap* GetStaticBitmap19() { return m_staticBitmap19; }
    wxStaticBitmap* GetStaticBitmap21() { return m_staticBitmap21; }
    wxStaticBitmap* GetStaticBitmap23() { return m_staticBitmap23; }
    wxStaticBitmap* GetStaticBitmap25() { return m_staticBitmap25; }
    wxStaticBitmap* GetStaticBitmap27() { return m_staticBitmap27; }
    wxStaticBitmap* GetStaticBitmap29() { return m_staticBitmap29; }
    wxStaticBitmap* GetStaticBitmap31() { return m_staticBitmap31; }
    wxStaticBitmap* GetStaticBitmap37() { return m_staticBitmap37; }
    wxStaticBitmap* GetStaticBitmap39() { return m_staticBitmap39; }
    wxStaticBitmap* GetStaticBitmap41() { return m_staticBitmap41; }
    wxStaticBitmap* GetStaticBitmap43() { return m_staticBitmap43; }
    wxStaticBitmap* GetStaticBitmap45() { return m_staticBitmap45; }
    wxStaticBitmap* GetStaticBitmap47() { return m_staticBitmap47; }
    wxMenuBar* GetMenuBar() { return m_menuBar; }
    wxToolBar* GetMainToolbar() { return m_mainToolbar; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("My Frame"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500,300), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
